/*DROP TABLE
DROP TABLE DEAN CASCADE CONSTRAINTS;
DROP TABLE PHANCONG CASCADE CONSTRAINTS;
DROP TABLE TAIKHOAN CASCADE CONSTRAINTS;
DROP TABLE PHONGBAN CASCADE CONSTRAINTS;
DROP TABLE NHANVIEN CASCADE CONSTRAINTS;
*/
--TAO PHONG BAN
CREATE TABLE PHONGBAN
(
    MAPB INT NOT NULL,
    TENPB VARCHAR2(50),
    TRPHG VARCHAR2(10),
    CONSTRAINT PK_PHONGBAN PRIMARY KEY(MAPB)
);
--TAO NHAN VIEN-- 
CREATE TABLE NHANVIEN
(
    MANV VARCHAR2(10) NOT NULL,
    TENNV VARCHAR2(50),
    PHAI VARCHAR2(5),
    NGAYSINH DATE,
    DIACHI VARCHAR2(50),
    SDT VARCHAR(20),
    LUONG FLOAT,
    PHUCAP FLOAT,
    VAITRO VARCHAR2(20),
    MANQL VARCHAR2(10),
    PHG INT,
    CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
);
--TAO DE AN--
CREATE TABLE DEAN
(
    MADA INT,
    TENDA VARCHAR(50),
    NGAYBD DATE,
    PHONG INT,
    CONSTRAINT PK_DEAN PRIMARY KEY(MADA)
);
--TAO PHAN CONG--
CREATE TABLE PHANCONG 
(
    MANV VARCHAR2(10),
    MADA INT,
    THOIGIAN INT,
    CONSTRAINT PK_PHANCONG PRIMARY KEY(MANV,MADA)
);
--TAO TAI KHOAN--
CREATE TABLE TAIKHOAN
(
    USERNAME VARCHAR2(20),
    PASS VARCHAR2(20),
    MANV VARCHAR2(10),
    CONSTRAINT PK_TAIKHOAN PRIMARY KEY(USERNAME,PASS)
);