ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE; 
/*
DROP ROLE R_NHANVIEN;
DROP ROLE R_QUANLY;
DROP ROLE R_TRUONGPHONG;
DROP ROLE R_TAICHINH;
DROP ROLE R_NHANSU;
DROP ROLE R_TRUONGDEAN;
*/

CREATE ROLE R_NHANVIEN;
CREATE ROLE R_QUANLY;
CREATE ROLE R_TRUONGPHONG;
CREATE ROLE R_TAICHINH;
CREATE ROLE R_NHANSU;
CREATE ROLE R_TRUONGDEAN;

--PHAN QUYEN ROLE NHAN VIEN
GRANT CREATE SESSION TO R_NHANVIEN;
GRANT SELECT ON NHANVIEN TO R_NHANVIEN;
GRANT SELECT ON PHANCONG TO R_NHANVIEN;
GRANT UPDATE(NGAYSINH,DIACHI,SDT) ON NHANVIEN TO R_NHANVIEN;
GRANT SELECT ON PHONGBAN TO R_NHANVIEN;
GRANT SELECT ON DEAN TO R_NHANVIEN;

--PHAN QUYEN CHO ROLE QUAN LY TRUC TIEP
GRANT SELECT ON NHANVIEN TO R_QUANLY;
GRANT SELECT ON PHANCONG TO R_QUANLY;
GRANT UPDATE(NGAYSINH,DIACHI,SDT) ON NHANVIEN TO R_QUANLY;
GRANT SELECT ON PHONGBAN TO R_QUANLY;
GRANT SELECT ON DEAN TO R_QUANLY;

--PHAN QUYEN CHO TRUONG PHONG
GRANT SELECT ON NHANVIEN TO R_TRUONGPHONG;
GRANT ALL ON PHANCONG TO R_TRUONGPHONG;
GRANT UPDATE(NGAYSINH,DIACHI,SDT) ON NHANVIEN TO R_TRUONGPHONG;
GRANT SELECT ON PHONGBAN TO R_TRUONGPHONG;
GRANT SELECT ON DEAN TO R_TRUONGPHONG;

--PHAN QUYEN CHO ROLE TAI CHINH
GRANT SELECT ON NHANVIEN TO R_TAICHINH;
GRANT SELECT ON PHANCONG TO R_TAICHINH;
GRANT UPDATE(NGAYSINH,DIACHI,SDT, LUONG, PHUCAP) ON NHANVIEN TO R_TAICHINH;
GRANT SELECT ON PHONGBAN TO R_TAICHINH;
GRANT SELECT ON DEAN TO R_TAICHINH;

--PHAN QUYEN CHO ROLE NHAN SU
GRANT SELECT ON NHANVIEN TO R_NHANSU;
GRANT SELECT ON PHANCONG TO R_NHANSU;
GRANT INSERT(MANV, TENNV, PHAI, NGAYSINH, DIACHI, SDT, VAITRO, MANQL, PHG), UPDATE(MANV, TENNV, PHAI, NGAYSINH, DIACHI, SDT, VAITRO, MANQL, PHG) ON NHANVIEN TO R_NHANSU;
GRANT SELECT, UPDATE, INSERT ON PHONGBAN TO R_NHANSU;
GRANT SELECT ON DEAN TO R_NHANSU;

--PHAN QUYEN ROLE TRUONG DE AN
GRANT SELECT ON NHANVIEN TO R_TRUONGDEAN;
GRANT SELECT ON PHANCONG TO R_TRUONGDEAN;
GRANT UPDATE(NGAYSINH,DIACHI,SDT) ON NHANVIEN TO R_TRUONGDEAN;
GRANT SELECT ON PHONGBAN TO R_TRUONGDEAN;
GRANT ALL ON DEAN TO R_TRUONGDEAN;