--CS#1
CREATE OR REPLACE VIEW UV_NHANVIEN
AS
    SELECT *
    FROM NHANVIEN 
    WHERE MANV = SYS_CONTEXT('USERENV','SESSION_USER') 
    WITH CHECK OPTION;
    
/
--SUA TTNV
CREATE OR REPLACE TRIGGER TRIGGER_UPDATE_NV
INSTEAD OF UPDATE
ON UV_NHANVIEN
FOR EACH ROW
DECLARE
BEGIN
    UPDATE NHANVIEN 
    SET NGAYSINH = :NEW.NGAYSINH,
        SDT = :NEW.PHAI,
        DIACHI = :NEW.DIACHI
    WHERE MANV = :NEW.MANV;
END;
/
GRANT SELECT, UPDATE(NGAYSINH, DIACHI, SDT) ON UV_NHANVIEN TO R_NHANVIEN, R_QUANLY, R_TRUONGPHONG, R_TRUONGDEAN, R_TAICHINH, R_NHANSU;

CREATE OR REPLACE VIEW UV_PHANCONG
AS
    SELECT *
    FROM PHANCONG 
    WHERE MANV = SYS_CONTEXT('USERENV','SESSION_USER')
    WITH CHECK OPTION;
GRANT SELECT ON UV_PHANCONG TO R_NHANVIEN, R_QUANLY, R_TRUONGPHONG, R_TRUONGDEAN, R_TAICHINH, R_NHANSU;

--CS#2
CREATE OR REPLACE VIEW UV_NHANVIEN_QL
AS
    SELECT *
    FROM NHANVIEN 
    WHERE MANV = SYS_CONTEXT('USERENV','SESSION_USER') OR MANQL = SYS_CONTEXT('USERENV','SESSION_USER')
    WITH CHECK OPTION;

GRANT SELECT ON UV_NHANVIEN_QL TO R_QUANLY;

CREATE OR REPLACE VIEW UV_PHANCONG_QL
AS
    SELECT *
    FROM PHANCONG 
    WHERE MANV = SYS_CONTEXT('USERENV','SESSION_USER') OR MANV IN (SELECT MANV FROM NHANVIEN WHERE MANQL = SYS_CONTEXT('USERENV','SESSION_USER'))
    WITH CHECK OPTION;

GRANT SELECT ON UV_PHANCONG_QL TO R_QUANLY;
--CS#3
CREATE OR REPLACE VIEW UV_NHANVIEN_TP
AS
    SELECT *
    FROM NHANVIEN 
    WHERE MANV = SYS_CONTEXT('USERENV','SESSION_USER') OR PHG = (SELECT MAPB FROM PHONGBAN WHERE TRPHG = SYS_CONTEXT('USERENV','SESSION_USER'))
    WITH CHECK OPTION;

GRANT SELECT ON UV_NHANVIEN_QL TO R_TRUONGPHONG;

CREATE OR REPLACE VIEW UV_PHANCONG_TP
AS
    SELECT *
    FROM PHANCONG 
    WHERE MANV = SYS_CONTEXT('USERENV','SESSION_USER') 
    OR MANV IN (SELECT MANV FROM NHANVIEN WHERE PHG = (SELECT MAPB FROM PHONGBAN WHERE TRPHG = SYS_CONTEXT('USERENV','SESSION_USER')))
    WITH CHECK OPTION;

GRANT SELECT, DELETE, INSERT, UPDATE(THOIGIAN) ON UV_PHANCONG_TP TO R_TRUONGPHONG;
/
--SUA PHAN CONG
CREATE OR REPLACE TRIGGER TRIGGER_UPDATE_PC 
INSTEAD OF UPDATE
ON UV_PHANCONG_TP
FOR EACH ROW
DECLARE
BEGIN
    IF :NEW.THOIGIAN IS NOT NULL
    THEN
        UPDATE PHANCONG 
        SET THOIGIAN = :NEW.THOIGIAN
        WHERE MANV = :NEW.MANV
        AND MADA = :NEW.MADA;
    END IF;
END;
/
--XOA PHAN CONG
CREATE OR REPLACE TRIGGER TRIGGER_DELETE_PC
INSTEAD OF DELETE
ON UV_PHANCONG_TP
FOR EACH ROW
DECLARE
BEGIN
    IF :OLD.MANV IS NOT NULL OR :OLD.MADA IS NOT NULL
    THEN
        DELETE FROM PHANCONG
        WHERE MANV = :OLD.MANV
        AND MADA = :OLD.MADA;
    END IF;
END;
/
--THEM PHAN CONG
CREATE OR REPLACE TRIGGER TRIGGER_INSERT_PC
INSTEAD OF INSERT
ON UV_PHANCONG_TP
FOR EACH ROW
DECLARE
BEGIN
    IF :NEW.MANV IS NOT NULL OR :NEW.MADA IS NOT NULL
    THEN
        INSERT INTO PHANCONG 
        VALUES(:NEW.MANV, :NEW.MADA, :NEW.THOIGIAN);
    END IF;
END;
/

--CS#5
CREATE OR REPLACE VIEW UV_NHANVIEN_NS
AS
    SELECT MANV, TENNV, PHAI, NGAYSINH, DIACHI, SDT, VAITRO, MANQL, PHG
    FROM NHANVIEN 

GRANT SELECT ON UV_NHANVIEN_NS TO R_NHANSU;
