
--AUDIT KHI CAP NHAT THOI GIAN TRONG PHAN CONG
--BEGIN DBMS_FGA.DROP_POLICY ('MNG', 'PHANCONG', 'PC_TG_AUDIT'); END;
BEGIN
  DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA   => 'MNG',
    OBJECT_NAME     => 'PHANCONG',
    POLICY_NAME     => 'PC_TG_AUDIT',
    AUDIT_COLUMN    => 'THOIGIAN',
    STATEMENT_TYPES => 'UPDATE');
END;
/
--AUDIT KHI DOC LUONG VA PHU CAP CUA NGUOI KHAC
--BEGIN DBMS_FGA.DROP_POLICY ('MNG', 'PHANCONG', 'L_PC_AUDIT'); END;
/
BEGIN
  DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA   => 'MNG',
    OBJECT_NAME     => 'NHANVIEN',
    POLICY_NAME     => 'L_PC_AUDIT',
    AUDIT_CONDITION => 'MANV <> ''' || SYS_CONTEXT('USERENV','SESSION_USER') || ''' ', 
    AUDIT_COLUMN    => 'LUONG,PHUCAP',
    STATEMENT_TYPES => 'SELECT');
END;
/

--AUDIT KHI CAP NHAT LUONG VA PHU CAP MA KHONG PHAI LA NHAN VIEN TAI CHINH
--BEGIN DBMS_FGA.DROP_POLICY ('MNG', 'PHANCONG', 'TC_AUDIT'); END;
/
BEGIN
  DBMS_FGA.ADD_POLICY(
    OBJECT_SCHEMA   => 'MNG',
    OBJECT_NAME     => 'NHANVIEN',
    POLICY_NAME     => 'TC_AUDIT',
    AUDIT_CONDITION => 'VAITRO <> TAICHINH', 
    AUDIT_COLUMN    => 'LUONG,PHUCAP',
    STATEMENT_TYPES => 'UPDATE');
END;
/

SELECT DB_USER,OBJECT_NAME,SQL_TEXT,EXTENDED_TIMESTAMP FROM dba_fga_audit_trail order by extended_timestamp desc;
   
