
--PROCEDURE DANG NHAP
CREATE OR REPLACE PROCEDURE USP_LOGIN ( PARA_USERNAME VARCHAR2, PARA_PASSWORD VARCHAR2, MANV OUT VARCHAR2, VAITRO OUT VARCHAR2)
AS BEGIN
    IF PARA_USERNAME = 'MNG' AND PARA_PASSWORD = '1' THEN
        SELECT 'MNG', 'MANAGER' INTO MANV, VAITRO FROM DUAL;
    ELSE
        SELECT TK.MANV, NV.VAITRO INTO MANV, VAITRO FROM MNG.TAIKHOAN TK JOIN MNG.NHANVIEN NV ON TK.MANV = NV.MANV
        WHERE TK.USERNAME = PARA_USERNAME AND TK.PASS = PARA_PASSWORD;
    END IF;
END;
/

--PROCEDURE TAO USER
CREATE OR REPLACE PROCEDURE USP_CREATEUSER ( PARA_USERNAME VARCHAR2, PARA_PASSWORD VARCHAR2)
AS
PARA_MANV VARCHAR2(8);
BEGIN
    SELECT MAX(CAST(SUBSTR(MANV,3) AS VARCHAR2(8))) + 1 INTO PARA_MANV FROM MNG.NHANVIEN;
        
    EXECUTE IMMEDIATE('ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE');
    EXECUTE IMMEDIATE('CREATE USER ' || PARA_USERNAME || ' IDENTIFIED BY ' || PARA_PASSWORD);
    
    INSERT INTO TAIKHOAN VALUES (PARA_USERNAME,PARA_PASSWORD,'NV' || CAST(PARA_MANV AS VARCHAR2(8)));
    INSERT INTO NHANVIEN(MANV) VALUES('NV' || CAST(PARA_MANV AS VARCHAR2(8)));
    
END;
/
--PROCEDURE XOA USER
CREATE OR REPLACE PROCEDURE USP_DROPUSER ( PARA_USERNAME VARCHAR2)
AS
PARA_MANV VARCHAR2(10);
BEGIN
    SELECT MANV INTO PARA_MANV FROM MNG.TAIKHOAN 
    WHERE USERNAME = PARA_USERNAME;
    
    EXECUTE IMMEDIATE('DROP USER ' || PARA_USERNAME);
    
    DELETE FROM NHANVIEN WHERE MANV = PARA_MANV;
    DELETE FROM TAIKHOAN WHERE MANV = PARA_MANV;
END;
/
--PROCEDURE THEM USER VAO ROLE
CREATE OR REPLACE PROCEDURE USP_ADDUSER_ROLE ( PARA_USER VARCHAR2, PARA_ROLE VARCHAR2)
AS
BEGIN
    EXECUTE IMMEDIATE('GRANT  ' || PARA_ROLE || ' TO ' || PARA_USER);
    
    UPDATE NHANVIEN
    SET VAITRO = PARA_ROLE
    WHERE MANV = (SELECT MANV FROM TAIKHOAN WHERE USERNAME = PARA_USER);
END;
/
-- PROCEDURE TAO ROLE
CREATE OR REPLACE PROCEDURE USP_CREATEROLE ( PARA_ROLE VARCHAR2)
AS
BEGIN
    EXECUTE IMMEDIATE('ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE');
    EXECUTE IMMEDIATE('CREATE ROLE ' || PARA_ROLE);
END;